### ISSUE TITLE
node-001: init container cannot download boot nodes

### ISSUE THREAD

**Issue by PabloCastellano** [ethpandaops/4844-testnet#102]
Hi. I'm deploying a devnet5 network on my local cluster by using the `node-001` chart. However it is not working since the  file at `BOOTNODE_URI` is not downloadable anymore:

https://github.com/ethpandaops/4844-testnet/blob/ca1aa3bb70f8e0637206d5b54e3a805a900a4995/kubernetes/devnet-5/node-001/values.yaml#L57-L71

https://github.com/ethpandaops/4844-testnet/blob/ca1aa3bb70f8e0637206d5b54e3a805a900a4995/kubernetes/devnet-5/node-001/values.yaml#L124-L143

```
$ kubectl logs -f prysm-geth-001-0 -c init-genesis

genesis exists. skipping...
cat: can't open '/data/testnet_spec/bootstrap_nodes.txt': No such file or directory
bootnode init done: 
```

**Comment by skylenet** [comment]
Change has been deployed and both addresses are working now:

- https://config.4844-devnet-5.ethpandaops.io/bootstrap_nodes.txt; 
- https://config.4844-devnet-5.ethpandaops.io/el/bootnodes
